


def locate(mus, grid, instru_map) :
    
    grid.set_num_box(6)
    grid.set_margin(10) 
    
    
    mus["Jean-Jacques_chef_totoro"            ].at(1,1,1)
    mus["Jean-Jacques_percu_totoro"           ].at(2,1,1)
    mus["Jean-Jacques_chef_laché prise"       ].at(3,1,1)
    mus["Alizee_piano_totoro"                 ].at(4,1,1)
    mus["Bidou_euphonium_totoro"              ].at(5,1,1)
    mus["Serge_euphonium_totoro"              ].at(6,1,1)
    mus["Amélie_clarinette_recadre"           ].at(1,2,1)
    mus["Nelly_clarinette_totoro"             ].at(2,2,1)
    mus["Natacha_clarinette_totoro"           ].at(3,2,1)
    mus["Pierre_clarinette_totoro_recadre"    ].at(4,2,1)
    mus["Anne-sonia_clarinette_totoro"        ].at(5,2,1)
    mus["Stephane_clarinette_totoro"          ].at(6,2,1)
    mus["PierreG_clarinette_totoro"           ].at(1,3,1)
    mus["Violette_clarinette_totoro"          ].at(2,3,1)
    mus["André_cor_totoro"                    ].at(3,3,1)
    mus["Alain_flute_totoro"                  ].at(4,3,1)
    mus["Laurence_flute_totoro"               ].at(5,3,1)
    mus["Antoine_flute_totoro"                ].at(6,3,1)
    mus["Gwenn_flute_totoro"                  ].at(1,4,1)
    mus["Aurélie_hautbois_totoro"             ].at(2,4,1)
    mus["Veronique_hautbois_totoro"           ].at(3,4,1)
    mus["Aurianne_saxophone_totoro"           ].at(4,4,1)
    mus["Marie-Claude_saxophone_totoro"       ].at(5,4,1)
    mus["Franck_saxophone_totoro"             ].at(6,4,1)
    mus["Nadine_saxophone_totoro"             ].at(1,5,1)
    mus["Nathalie_saxophone_totoro"           ].at(2,5,1)
    mus["Chloe_saxophone_totoro_clown_recadre"].at(3,5,1)
    mus["Camille_trombone_totoro"             ].at(4,5,1)
    mus["daniel_trombone_totoro"              ].at(5,5,1)
    mus["Bidou_cornet_totoro"                 ].at(6,5,1)
    mus["Serge_trompette_totoro"              ].at(1,6,1)
    mus["Patrick_trompette_totoro"            ].at(2,6,1)
    mus["Marianne_trompette_totoro"           ].at(3,6,1)
    mus["Svoisine_tuba"                       ].at(4,6,1)
    mus["Serge_baryton_totoro_recadre"        ].at(5,6,1)
    mus["Srevol_tuba_recadre"                 ].at(6,6,1)
